import "@/app/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>LWS Xstream - Video Streaming</title>
      </head>
      <body className="bg-color-bg text-white font-exo">
        <div className="container mx-auto px-4 py-4">
          {children}
          <div id="modal-root-content"></div>
        </div>
      </body>
    </html>
  );
}
