import "@/app/globals.css";
import Header from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal, params: { lang } }) {
  return (
    <>
      <Header lang={lang} />
      {modal}
      {children}
    </>
  );
}
